### PR TITLE
Added compatibility flags for gcc-10+

### PR DESCRIPTION
**Pull request by fdeugenio**
This should solve the issue https://github.com/JohannesBuchner/PyMultiNest/issues/166

It does for me.

Cheers,
Francesco

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
That flag only exists in gcc 10, won't that cause issues for gcc<10?

**Comment by fdeugenio** [comment]
Ah, let me test that! Sorry I didn't know that

**Comment by fdeugenio** [comment]
I added an if to maintain backwards compatibility. I can confirm it works with 10+ and 6.3, but the exact divide between using or not the flag depends on what happens with e.g. 8 and 9.3.

I'll be able to test it tomorrow. In the meantime, are you in a position to test with 4.7 < gfortran < 6.3?

**Comment by JohannesBuchner** [comment]
I wonder if this is identical with the issue of https://github.com/JohannesBuchner/PyMultiNest/issues/174

Perhaps we should fix the errors (correct the types) instead of hiding them.

**Comment by JohannesBuchner** [comment]
I think you want the check within the GNU-if, otherwise you will get troubles with other compilers (e.g., icc).

**Comment by JohannesBuchner** [comment]
which would be https://github.com/farhanferoz/MultiNest/pull/8/files I think.

**Comment by fdeugenio** [comment]
Sorry, did not even know people use those... I think I fixed it, but please wait for me to test it tomorrow on gfortan 8 to 9.
Also, I have no idea how to test it on icc (or other compilers you are supporting). Perhaps that's something you could do?

**Comment by fdeugenio** [comment]
To recap, I tested and can confirm this commit works with
gcc-8+ (including gcc-10+)
gcc-6.3

**Pull request merged**
