### PR TITLE
Allow longer file names

### PR DESCRIPTION
**Pull request by mattpitkin**
In v3.12 of MultiNest is allows file names up to 1000 characters long. It would be good to have this feature in this version too. This would help the use of PyMultinest as implemented through bilby, which uses the conda install of MultiNest based off this repo.

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
I have been hesitant to make this upgrade, because it breaks backwards compatibility. So far, any MultiNest version (except for the last) is compatible with the latest PyMultiNest.
Current workarounds include making softlinks, or chdir'ing into the target directory.

**Comment by mattpitkin** [comment]
Ah, I hadn't realised it would cause issues with his things interacted with PyMultinest! People have been using those workarounds, but links and temporary local directories seem to become problematic when using MPI on a cluster. If you think it wouldn't be too much work myself or another bilby developer could look at making a PR for PyMultinest to fix this compatibility?

**Comment by mattpitkin** [comment]
Would it just be editing this line https://github.com/JohannesBuchner/PyMultiNest/blob/master/pymultinest/run.py#L237, or is there something more involved?

**Comment by JohannesBuchner** [comment]
The fix is trivial, but it requires everyone to sync the versions on all their computers.

**Comment by JohannesBuchner** [comment]
Why can you not chdir before pymultinest.run_nested?

**Comment by JohannesBuchner** [comment]
And why are softlinks problematic on a cluster?

**Comment by mattpitkin** [comment]
It seems I'd slightly misunderstood the cluster issue and some workarounds are possible, just a bit more of a pain to implement.

It would still be nice to have this fix, but I guess it would need some more complex checking of the versioning in the PyMultinest pip and conda builds.

**Comment by JohannesBuchner** [comment]
Yes, in some older pymultinest version I tried to detect the loaded multinest version. But I don't see how this would be possible for this particular change.

**Comment by mattpitkin** [comment]
In testing a change to PyMultiNest to detect the MultiNest version and set the filename buffer size accordingly, I actually found that the v3.11/12 change to MutliNest to allow 1000 character file names was actually broken! It works for the FORTRAN version, but is broken in the C wrapper as used by PyMultiNest. I've made a PR for this on Farhan's repo https://github.com/farhanferoz/MultiNest/pull/6 and have made equivalent changes here.

**Comment by JohannesBuchner** [comment]
Could you test if a updated PyMultiNest can be made to work with both v3.11 and v3.12(corrected)? I suspect it will cause issues if we declare the ctypes to 1000 chars.

If a ctype with 100 chars works for both versions, we could make a compromise: use 100 chars unless >100 chars are needed, in which case 1000 chars are needed. Then the behaviour changes (TBC) from truncation to segfaulting if the MultiNest version is v3.11.

**Comment by mattpitkin** [comment]
> If a ctype with 100 chars works for both versions, we could make a compromise: use 100 chars unless >100 chars are needed, in which case 1000 chars are needed. Then the behaviour changes (TBC) from truncation to segfaulting if the MultiNest version is v3.11.

I've just checked and having the ctype being 100 chars works for both versions, so I think your compromise will work.

**Comment by mattpitkin** [comment]
@JohannesBuchner would you be able to create a new branch in your repo and merge this into that branch (so we don't have to merge into master yet)? I can then test the travis CI for PyMultiNest.

**Comment by JohannesBuchner** [comment]
I think you can activate travis in your fork?

**Comment by JohannesBuchner** [comment]
at https://travis-ci.org/github/mattpitkin/MultiNest-1/branches

**Comment by mattpitkin** [comment]
Ah yes! I'll give that a go first. Thanks.

**Comment by mattpitkin** [comment]
Just a note that Farhan has now merged https://github.com/farhanferoz/MultiNest/pull/6 into his MultiNest repo.

**Pull request merged**
